/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tk1_kelompok_5.Frame_Dasboard;

/**
 *
 * @author Sirdzat
 */
public class frameDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frameDashboard.class.getName());

    /**
     * Creates new form frameDashboard
     */
    public frameDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        openNadira = new javax.swing.JLabel();
        openSaiful = new javax.swing.JLabel();
        openFaris = new javax.swing.JLabel();
        openSirdzat = new javax.swing.JLabel();
        openWaffa = new javax.swing.JLabel();
        openAnam = new javax.swing.JLabel();
        biodata = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        backgroung = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        openNadira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk1_kelompok_5/Frame_Dasboard/Group 25.png"))); // NOI18N
        jPanel1.add(openNadira, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 240, 40, 110));

        openSaiful.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk1_kelompok_5/Frame_Dasboard/Group 25.png"))); // NOI18N
        jPanel1.add(openSaiful, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 40, 110));

        openFaris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk1_kelompok_5/Frame_Dasboard/Group 25.png"))); // NOI18N
        jPanel1.add(openFaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, 40, 110));

        openSirdzat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk1_kelompok_5/Frame_Dasboard/Group 25.png"))); // NOI18N
        jPanel1.add(openSirdzat, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 390, 40, 110));

        openWaffa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk1_kelompok_5/Frame_Dasboard/Group 25.png"))); // NOI18N
        jPanel1.add(openWaffa, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 40, 110));

        openAnam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk1_kelompok_5/Frame_Dasboard/Group 25.png"))); // NOI18N
        jPanel1.add(openAnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(933, 390, 40, 110));

        biodata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk1_kelompok_5/Frame_Dasboard/Group 27.png"))); // NOI18N
        jPanel1.add(biodata, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk1_kelompok_5/Frame_Dasboard/Group 28.png"))); // NOI18N
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, -1, -1));

        backgroung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk1_kelompok_5/Frame_Dasboard/Group 26.png"))); // NOI18N
        jPanel1.add(backgroung, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frameDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroung;
    private javax.swing.JLabel biodata;
    private javax.swing.JLabel close;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel openAnam;
    private javax.swing.JLabel openFaris;
    private javax.swing.JLabel openNadira;
    private javax.swing.JLabel openSaiful;
    private javax.swing.JLabel openSirdzat;
    private javax.swing.JLabel openWaffa;
    // End of variables declaration//GEN-END:variables
}
